version: "3"

services:
  db:
    privileged: true
    image: mariadb
    container_name: mysql_service
    volumes:
      - db_conf:/etc/mysql/conf.d
      - db_data:/var/lib/mysql
    env_file: .env
    environment:
      TZ: Asia/Seoul
    networks:
      - backend
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    restart: always

  server:
    build: ./server/
    container_name: algotalk_server
    ports:
      - 5005:5005
    volumes:
      - git:/home/algotalk_rasa
    networks:
      - backend
    depends_on:
      - db
    stdin_open: true    # docker run -i
    tty: true           # docker run -t
    restart: always

networks:
  backend:

volumes:
  db_conf:
  db_data:
  git:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /C:/dev/docker/algotalk/git/algotalk_rasa